# Generated by Django 3.1.1 on 2020-09-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_game_studios'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='studios',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
        migrations.AddField(
            model_name='game',
            name='voice_actors',
            field=models.ManyToManyField(to='main_app.VoiceActor'),
        ),
    ]
