# Generated by Django 3.1.1 on 2020-09-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200917_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='voice_actors',
        ),
    ]
