# Generated by Django 3.1.1 on 2020-09-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_game_voice_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='voice_actors',
            field=models.ManyToManyField(to='main_app.VoiceActor'),
        ),
    ]
